name: Pay and Connect Voucher Request

on:
    schedule:
    - cron: '01 19 * * 0-4'
  
jobs:
  request:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: "18.15"

    - name: Install Dependencies
      run: npm install
    - name: Setting the environment variables
      run: |
        echo "STUDENT_EMAIL=$STUDENT_EMAIL" >> $GITHUB_ENV
        echo "STUDENT_PASSWORD=$STUDENT_PASSWORD" >> $GITHUB_ENV
        echo "NOTIFICATION_EMAIL=$NOTIFICATION_EMAIL" >> $GITHUB_ENV
        echo "NOTIFICATION_EMAIL_PASSWORD=$NOTIFICATION_EMAIL_PASSWORD" >> $GITHUB_ENV
      
      env:
        STUDENT_EMAIL: ${{ secrets.STUDENT_EMAIL }}
        STUDENT_PASSWORD: ${{ secrets.STUDENT_PASSWORD }}
        NOTIFICATION_EMAIL: ${{ secrets.NOTIFICATION_EMAIL }}
        NOTIFICATION_EMAIL_PASSWORD: ${{ secrets.NOTIFICATION_EMAIL_PASSWORD }}
   

    - name: Run Program
      run: npm start

                
            
